### ISSUE TITLE
Provide 'extras' for installing optional packages

### ISSUE THREAD

**Issue by brettcannon** [achael/eht-imaging#101]
Looking at https://github.com/achael/eht-imaging/blob/master/setup.py I noticed 4 dependencies commented out due to them only being necessary for optional things. This sort of thing is a perfect use for ["extras" installs](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies). It lets users [specify the "extras" they want](https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras) and then only get bonus features if they want them.

**Comment by aadibajpai** [comment]
I observed that as well, made a PR.
