### ISSUE TITLE
No NFFT Installed issue

### ISSUE THREAD

**Issue by bellab4710** [achael/eht-imaging#139]
**Describe the bug**
Program says that no NFFT is installed after following installation instructions in the README.

**To Reproduce**
1.Install NFFT and pynfft with conda as described in readme
2. Clone repository
3. Build with dockerfile
3. Run dockerfile
4. Run first 35 lines of examples/examples.py in ipython

**Expected behavior**
Running line 35 causes an error. I ran on both linux and MacOS; in the first case I got an issue that said no NFFT is installed, in the second I got an error that says 'NFFT is not defined.'

**Screenshots**

**Desktop (please complete the following information):**
 macOS Catalina
linux centOS Fedora

**Comment by jrfarah** [comment]
Please post the file and a reproduction line you're experiencing the error on.

You can also try replacing the "nfft" option with "direct" to avoid the nfft install problem altogether.

**Comment by bellab4710** [comment]
The file I'm going off of is https://github.com/achael/eht-imaging/blob/main/examples/example.py. I've been copy/pasting the lines into my ipython shell after running the container through docker. The error happens when I execute line 35: 
<img width="1033" alt="Screen Shot 2021-06-04 at 1 35 43 PM" src="https://user-images.githubusercontent.com/84340108/120859962-cc84e000-c539-11eb-928d-2b615c28fa0a.png">

**Comment by jrfarah** [comment]
That seems to be a problem in `eht-imaging`. For line 35, can you try running this instead in the meantime:

`obs = im.observe(eht, tint_sec, tadv_sec, tstart_hr, tstop_hr, bw_hz, sgrscat=False, ampcal=True, phasecal=False, ttype='direct')`

That should let you continue in the script.

**Comment by bellab4710** [comment]
That worked thank you!
