### ISSUE TITLE
Remove requirement for jupyter?

### ISSUE THREAD

**Issue by aaron-sao** [achael/eht-imaging#149]
This line seems not to be necessary - the import isn't used and I successfully used the library without it. If removed, eht-imaging will no longer require the installation of the jupyter libraries, which would be nice.

https://github.com/achael/eht-imaging/blob/bbd3aeb06bef52bf89fa1c06de71e5509a5b0015/ehtim/modeling/modeling_utils.py#L49

**Comment by achael** [comment]
this was removed in ehtim 1.2.4, sorry for not closing the issue earlier
