### ISSUE TITLE
pyNFFT for M1 Mac (M1 Pro, M1 Max etc.)

### ISSUE THREAD

**Issue by rohandahale** [achael/eht-imaging#161]
```conda install -c conda-forge pynfft``` will not work for newer M1 Mac / M1 Pro / M1 Max

I have forked the [pyNFFT](https://github.com/pyNFFT/pyNFFT.git) git repository here https://github.com/rohandahale/pyNFFT.git and I have written down step-by-step instructions for installing pyNFFT on M1 Macs. I have also made small edit to the ```setup.py``` file to use ```gcc-12``` as the C compiler which works the best for installation with ```openmp```.

It could be helpful if this repository link is added as a small note for ```pynfft``` installation in the ``` README.md```.

**Comment by achael** [comment]
hi @rohandahale apologies for the late action on this. Do you want to make a pull request updating the readme with these instructions for macs?

**Comment by rohandahale** [comment]
Hi @achael, no worries. I just create a pull request #168 to the main branch.
