### ISSUE TITLE
Lastest numpy 1.24.2 does not work with ehtim

### ISSUE THREAD

**Issue by rohandahale** [achael/eht-imaging#165]
`pip install ehtim` will install numpy 1.24.2. In a python 3.8 shell when you do `import ehtim`, you will get an error:

`ImportError: cannot import name 'bool' from 'numpy' `

The correct way to install ehtim should be:

`pip install ehtim numpy==1.21.1`

**Comment by Bravco** [comment]
You are correct.

**Comment by shitwolfymakes** [comment]
Is this still active? There's a number of bugs and code duplication I could fix but it won't mean much if it doesn't get merged

**Comment by wumpus** [comment]
This particular problem is already fixed in the dev branch. @achael prefers that you make bugfixes (hopefully tested!) against the dev branch.

If you have additional bugs or see code duplication, please open separate issues.

**Comment by wumpus** [comment]
This particular problem is already fixed in the dev branch. @achael prefers that you make bugfixes (hopefully tested!) against the dev branch.

If you have additional bugs or see code duplication, please open separate issues.

**Comment by shitwolfymakes** [comment]
Not referring to this, asking about the project as a whole. I already opened #164

**Comment by wumpus** [comment]
As a whole, the project is quite active. I was about to comment on that PR.

**Comment by shitwolfymakes** [comment]
Copy, thanks

**Comment by rohandahale** [comment]
This is issue is closed. 

To install ehtim 1.2.4 please do:

**Comment by rohandahale** [comment]
This is issue is closed now but I will keep it open for people to see this.

To install eht-imaging 1.2.4 use pip with numpy 1.21.1:
`pip install ehtim numpy==1.21.1`

To install eht-imaging 1.2.5 use the dev branch on GitHub:
`git clone --branch dev https://github.com/achael/eht-imaging.git`

```
cd eht-imaging
python setup.py build
python setup.py install

pip install pandas==2.0.1 matplotlib==3.7.1 packaging astropy==5.2.2 hdrhistogram skyfield

conda install scikit-image networkx
conda install -c conda-forge pynfft
```
For M1 Pro and M1 Max chips, follow the issue #161 for NFFT installation and not the pynfft on conda.

**Comment by achael** [comment]
thank you @rohandahale and apologies for the late action on this. I will investigate next week if we can easily make ehtim compatible with numpy 1.2.4. and make a new release

**Comment by achael** [comment]
eht-imaging 1.2.5 seems to be working with numpy version 1.24 at the moment (though please raise an issue if anything else comes up). Since @rohandahale's installation instructions for M1 macs has been added to the README, I am now closing this issue.
