### ISSUE TITLE
Observations cannot generate tlists(), possibly due to ragged arrays being abandoned in numpy 1.24.

### ISSUE THREAD

**Issue by danielpalumbo** [achael/eht-imaging#167]
Hi,

After loading an observation, calling obs.tlist() throws the error "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (72,) + inhomogeneous part." where the 72 is case-specific. Is there a recommended workaround or should I backdate numpy?

**Comment by achael** [comment]
can you provide a short example and your numpy version so I can verify if this is indeed a numpy issue and where in the code it occurs?

**Comment by danielpalumbo** [comment]
Sure. I am using numpy 1.24.3.

As an example, run the first 36 lines of eht-imaging's example.py, and then call obs.tlist(). See below:


`# Note: this is an example sequence of commands to run in ipython
# The matplotlib windows may not open/close properly if you run this directly as a script

from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import ehtim as eh
from   ehtim.calibrating import self_cal as sc
import time
#from  ehtim.plotting import self_cal as sc
plt.close('all')

ttype = 'direct'

# Load the image and the array
im = eh.image.load_txt('../models/avery_sgra_eofn.txt')
eht = eh.array.load_txt('../arrays/EHT2017.txt')

# Look at the image
im.display()

# Observe the image
# tint_sec is the integration time in seconds, and tadv_sec is the advance time between scans
# tstart_hr is the GMST time of the start of the observation and tstop_hr is the GMST time of the end
# bw_hz is the  bandwidth in Hz
# sgrscat=True blurs the visibilities with the Sgr A* scattering kernel for the appropriate image frequency
# ampcal and phasecal determine if gain variations and phase errors are included
tint_sec = 5
tadv_sec = 600
tstart_hr = 0
tstop_hr = 24
bw_hz = 4e9
obs = im.observe(eht, tint_sec, tadv_sec, tstart_hr, tstop_hr, bw_hz,
                 sgrscat=False, ampcal=True, phasecal=False)
obs.tlist()`

**Comment by danielpalumbo** [comment]
Fwiw, a fresh install forcing numpy=1.22 seems to resolve this issue.

**Comment by achael** [comment]
I seem to have fixed this issue in numpy 1.24 by reverting to the previous call "np.array(datalist, dtype=object)". I think this was removed several years ago due to a warning message, but it works in 1.22 and 1.24 without a message and returns the same result.

**Comment by achael** [comment]
since this is working for me with numpy 1.24 i am closing the issue for now, let me know if it crops up again.
