### ISSUE TITLE
Conda fails to install `skyfield` or `paramsurvey[ray]` during project configuration

### ISSUE THREAD

**Issue by shitwolfymakes** [achael/eht-imaging#176]
**Describe the bug**
See title.

**To Reproduce**
Open up the project in pycharm and let it try to install all dependencies, then open up requirements.txt

**Expected behavior**
Both packages should be installed properly.

**Desktop (please complete the following information):**
 - OS: Debian 11 Bullseye

**Remediation**
In a terminal in the project folder, running `pip install skyfield paramsurvey` successfully installs the packages.

Additionally, it seems that the packages install by pip are newer than the ones in the conda repos

**Comment by shitwolfymakes** [comment]
Looking into the dependencies further, it seems like you have skyfield and paramsurvey defined in the requirements.txt, but not in anaconda's environment.yml. Which package manager are you trying to use for this project?

**Comment by shitwolfymakes** [comment]
Additionally, Jupyter is not installed by conda, and attempting to do so with conda fails. `pip install jupyter` works though

**Comment by achael** [comment]
Sorry for the long delay in getting to this issue. In the dev branch https://github.com/achael/eht-imaging/tree/dev, we have removed the deprecated environment.yml and updated all requirements in setup.py. We will merge the dev branch into the main branch shortly. Thanks again!
