### ISSUE TITLE
Missing `*` in eht-imaging/ehtim /image.py

### ISSUE THREAD

**Issue by gfparaschos** [achael/eht-imaging#180]
In line 3503 of the file in the title an asterisk is missing. It should be:
`factor *= beamarea / (self.psize**2)`.
Without the asterisk, setting `cbar_unit` equal to either `['mJy', 'beam']` or `['Jy', 'beam']` yields the same result.

**Comment by achael** [comment]
Thanks for catching this! This should be fixed now.
