### ISSUE TITLE
Warnings in ehtim_tutorial.ipynb

### ISSUE THREAD

**Issue by AlexKurek** [achael/eht-imaging#185]
There are 4 warnings here:
https://github.com/achael/eht-imaging/blob/main/tutorials/ehtim_tutorial.ipynb
colored in red. The first one:

> No NX table in uvfits!
> /home/achael/anaconda3/lib/python3.8/site-packages/erfa/core.py:154: ErfaWarning: ERFA function "d2dtf" yielded 212584 of "dubious year (Note 5)"
>   warnings.warn('ERFA function "{}" yielded {}'.format(func_name, wmsg),

**Comment by achael** [comment]
Sorry for the long delay in getting to this issue! I have updated the tutorials in the dev branch (https://github.com/achael/eht-imaging/tree/dev) and I don't see this issue any more. I will merge the dev branch with the main branch soon. Thanks again for your patience!
