### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ptiede** [achael/eht-imaging#196]
Would it be possible to release a new version of eht-imaging? Several critical bug fixes have been fixed recently in the dev branch, and I'd like to force users to use the latest version of eht-imaging in some of my downstream packages. Unfortunately, I'll need a tagged release to enforce this.

**Comment by shitwolfymakes** [comment]
New version and better unit tests will be nice, I'm itching to get back to work on this

**Comment by achael** [comment]
Sorry for the delays, I have just released v1.2.9 with all the dev branch bug fixes, I will hopefully finish the unit tests and data/imager updates sometime in the new year for v1.3

**Comment by ptiede** [comment]
Thanks so much!
