### ISSUE TITLE
Closure phases locked at zero and clip setting

### ISSUE THREAD

**Issue by jrcallingham** [achael/eht-imaging#50]
Hi again Andrew,

After that last error, the script is running but there is a couple of features I do not quite understand. For one, the chi2_1 (representing phase) is set to zero and does not change at all in the convergence processes. I do not know why that is the case, the output is below and my call to imag_func.

Also, the script outputs that the Total Pixel #:  16384 and Clipped Pixel #:  16384. That does not make a lot of sense to me, as how can all the pixels be clipped?

Sorry again if I am missing something simple.

Joe

`
Using closure phase and closure amplitude separately.
Warning! Specified flux is > 120% of maximum visibility amplitude!
Getting bispectra:: type vis, count min, scan 3371/3371 

Getting closure amps:: type vis camp , count min, scan 3371/3371

Initial S_1: -0.000000 S_2: -0.000000 S_3: 0.000000
Initial Chi^2_1: 0.000000 Chi^2_2: 1244289.391793 Chi^2_3: 1.000000
Initial Objective Function: 326493584.274608
Total Data 1:  70791
Total Data 2:  67420
Total Pixel #:  16384
Clipped Pixel #:  16384

i: 0 chi2_1: 0.00 chi2_2: 1244289.39 chi2_3: 1.00 s_1: 0.00 s_2: 0.00 s_3: 0.00
i: 1 chi2_1: 0.00 chi2_2: 126347.43 chi2_3: 1.00 s_1: 0.03 s_2: 0.03 s_3: 0.00
i: 2 chi2_1: 0.00 chi2_2: 107404.42 chi2_3: 1.00 s_1: 0.03 s_2: 0.03 s_3: 0.00
i: 3 chi2_1: 0.00 chi2_2: 95902.42 chi2_3: 1.00 s_1: 0.03 s_2: 0.03 s_3: 0.00
i: 4 chi2_1: 0.00 chi2_2: 51008.25 chi2_3: 1.00 s_1: 0.04 s_2: 0.04 s_3: 0.00
i: 5 chi2_1: 0.00 chi2_2: 30726.60 chi2_3: 1.00 s_1: 0.05 s_2: 0.05 s_3: 0.00
i: 6 chi2_1: 0.00 chi2_2: 4324.99 chi2_3: 1.00 s_1: 0.31 s_2: 0.31 s_3: 0.00
i: 7 chi2_1: 0.00 chi2_2: 511.05 chi2_3: 1.00 s_1: 5.37 s_2: 5.37 s_3: 0.00
i: 8 chi2_1: 0.00 chi2_2: 774.29 chi2_3: 1.00 s_1: 80.65 s_2: 80.65 s_3: 0.00
i: 9 chi2_1: 0.00 chi2_2: 5.80 chi2_3: 1.00 s_1: 285.23 s_2: 285.23 s_3: 0.00
i: 10 chi2_1: 0.00 chi2_2: 27.71 chi2_3: 1.00 s_1: 292.61 s_2: 292.61 s_3: 0.00
i: 11 chi2_1: 0.00 chi2_2: 49.97 chi2_3: 1.00 s_1: 350.60 s_2: 350.60 s_3: 0.00
i: 12 chi2_1: 0.00 chi2_2: 43.36 chi2_3: 1.00 s_1: 413.17 s_2: 413.17 s_3: 0.00
i: 13 chi2_1: 0.00 chi2_2: 26.81 chi2_3: 1.00 s_1: 495.87 s_2: 495.87 s_3: 0.00
i: 14 chi2_1: 0.00 chi2_2: 28.83 chi2_3: 1.00 s_1: 533.62 s_2: 533.62 s_3: 0.00
i: 15 chi2_1: 0.00 chi2_2: 15.65 chi2_3: 1.00 s_1: 577.21 s_2: 577.21 s_3: 0.00
i: 16 chi2_1: 0.00 chi2_2: 16.63 chi2_3: 1.00 s_1: 608.58 s_2: 608.58 s_3: 0.00
i: 17 chi2_1: 0.00 chi2_2: 9.78 chi2_3: 1.00 s_1: 615.92 s_2: 615.92 s_3: 0.00
i: 18 chi2_1: 0.00 chi2_2: 8.06 chi2_3: 1.00 s_1: 637.82 s_2: 637.82 s_3: 0.00
i: 19 chi2_1: 0.00 chi2_2: 9.04 chi2_3: 1.00 s_1: 641.03 s_2: 641.03 s_3: 0.00
i: 20 chi2_1: 0.00 chi2_2: 11.15 chi2_3: 1.00 s_1: 677.38 s_2: 677.38 s_3: 0.00
i: 21 chi2_1: 0.00 chi2_2: 0.55 chi2_3: 1.00 s_1: 691.50 s_2: 691.50 s_3: 0.00
i: 22 chi2_1: 0.00 chi2_2: 6.49 chi2_3: 1.00 s_1: 694.04 s_2: 694.04 s_3: 0.00
i: 23 chi2_1: 0.00 chi2_2: 8.52 chi2_3: 1.00 s_1: 695.83 s_2: 695.83 s_3: 0.00
i: 24 chi2_1: 0.00 chi2_2: 2.66 chi2_3: 1.00 s_1: 701.40 s_2: 701.40 s_3: 0.00
i: 25 chi2_1: 0.00 chi2_2: 3.82 chi2_3: 1.00 s_1: 706.82 s_2: 706.82 s_3: 0.00
i: 26 chi2_1: 0.00 chi2_2: 1.32 chi2_3: 1.00 s_1: 710.09 s_2: 710.09 s_3: 0.00
i: 27 chi2_1: 0.00 chi2_2: 1.79 chi2_3: 1.00 s_1: 712.76 s_2: 712.76 s_3: 0.00
i: 28 chi2_1: 0.00 chi2_2: 1.21 chi2_3: 1.00 s_1: 714.99 s_2: 714.99 s_3: 0.00
i: 29 chi2_1: 0.00 chi2_2: 1.07 chi2_3: 1.00 s_1: 714.74 s_2: 714.74 s_3: 0.00
i: 30 chi2_1: 0.00 chi2_2: 0.90 chi2_3: 1.00 s_1: 714.46 s_2: 714.46 s_3: 0.00
i: 31 chi2_1: 0.00 chi2_2: 0.65 chi2_3: 1.00 s_1: 714.57 s_2: 714.57 s_3: 0.00
i: 32 chi2_1: 0.00 chi2_2: 0.42 chi2_3: 1.00 s_1: 715.06 s_2: 715.06 s_3: 0.00
i: 33 chi2_1: 0.00 chi2_2: 0.34 chi2_3: 1.00 s_1: 715.62 s_2: 715.62 s_3: 0.00
i: 34 chi2_1: 0.00 chi2_2: 0.26 chi2_3: 1.00 s_1: 716.15 s_2: 716.15 s_3: 0.00
i: 35 chi2_1: 0.00 chi2_2: 0.25 chi2_3: 1.00 s_1: 716.34 s_2: 716.34 s_3: 0.00
i: 36 chi2_1: 0.00 chi2_2: 0.23 chi2_3: 1.00 s_1: 716.70 s_2: 716.70 s_3: 0.00
i: 37 chi2_1: 0.00 chi2_2: 0.21 chi2_3: 1.00 s_1: 717.02 s_2: 717.02 s_3: 0.00
i: 38 chi2_1: 0.00 chi2_2: 0.20 chi2_3: 1.00 s_1: 717.20 s_2: 717.20 s_3: 0.00
time: 464.397219 s
J: 1344.529552
Final Chi^2_1: 0.000000 Chi^2_2: 0.202248  Chi^2_3: 1.000000
CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
Warning! Specified flux is > 120% of maximum visibility amplitude!
Getting bispectra:: type vis, count min, scan 3371/3371 

Getting closure amps:: type vis camp , count min, scan 3371/3371

Initial S_1: -0.000000 S_2: -0.000000 S_3: 0.000000
Initial Chi^2_1: 0.000000 Chi^2_2: 0.290918 Chi^2_3: 1.000000
Initial Objective Function: -85.130163
Total Data 1:  70791
Total Data 2:  67420
Total Pixel #:  16384
Clipped Pixel #:  16384

i: 0 chi2_1: 0.00 chi2_2: 0.29 chi2_3: 1.00 s_1: 0.00 s_2: 0.00 s_3: 0.00
i: 1 chi2_1: 0.00 chi2_2: 0.28 chi2_3: 1.00 s_1: 0.00 s_2: 0.00 s_3: 0.00
i: 2 chi2_1: 0.00 chi2_2: 0.28 chi2_3: 1.00 s_1: 0.00 s_2: 0.00 s_3: 0.00
i: 3 chi2_1: 0.00 chi2_2: 0.25 chi2_3: 1.00 s_1: 0.02 s_2: 0.02 s_3: 0.00
i: 4 chi2_1: 0.00 chi2_2: 0.25 chi2_3: 1.00 s_1: 0.02 s_2: 0.02 s_3: 0.00
i: 5 chi2_1: 0.00 chi2_2: 0.24 chi2_3: 1.00 s_1: 0.05 s_2: 0.05 s_3: 0.00
i: 6 chi2_1: 0.00 chi2_2: 0.22 chi2_3: 1.00 s_1: 0.09 s_2: 0.09 s_3: 0.00
i: 7 chi2_1: 0.00 chi2_2: 0.21 chi2_3: 1.00 s_1: 0.19 s_2: 0.19 s_3: 0.00
i: 8 chi2_1: 0.00 chi2_2: 0.20 chi2_3: 1.00 s_1: 0.19 s_2: 0.19 s_3: 0.00
i: 9 chi2_1: 0.00 chi2_2: 0.19 chi2_3: 1.00 s_1: 0.28 s_2: 0.28 s_3: 0.00
i: 10 chi2_1: 0.00 chi2_2: 0.19 chi2_3: 1.00 s_1: 0.35 s_2: 0.35 s_3: 0.00
i: 11 chi2_1: 0.00 chi2_2: 0.18 chi2_3: 1.00 s_1: 0.43 s_2: 0.43 s_3: 0.00
i: 12 chi2_1: 0.00 chi2_2: 0.18 chi2_3: 1.00 s_1: 0.48 s_2: 0.48 s_3: 0.00
i: 13 chi2_1: 0.00 chi2_2: 0.17 chi2_3: 1.00 s_1: 0.56 s_2: 0.56 s_3: 0.00
i: 14 chi2_1: 0.00 chi2_2: 0.16 chi2_3: 1.00 s_1: 0.65 s_2: 0.65 s_3: 0.00
i: 15 chi2_1: 0.00 chi2_2: 0.16 chi2_3: 1.00 s_1: 0.65 s_2: 0.65 s_3: 0.00
i: 16 chi2_1: 0.00 chi2_2: 0.16 chi2_3: 1.00 s_1: 0.71 s_2: 0.71 s_3: 0.00
i: 17 chi2_1: 0.00 chi2_2: 0.16 chi2_3: 1.00 s_1: 0.72 s_2: 0.72 s_3: 0.00
i: 18 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.77 s_2: 0.77 s_3: 0.00
i: 19 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.77 s_2: 0.77 s_3: 0.00
i: 20 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.79 s_2: 0.79 s_3: 0.00
i: 21 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.81 s_2: 0.81 s_3: 0.00
i: 22 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.80 s_2: 0.80 s_3: 0.00
i: 23 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.82 s_2: 0.82 s_3: 0.00
i: 24 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.82 s_2: 0.82 s_3: 0.00
i: 25 chi2_1: 0.00 chi2_2: 0.15 chi2_3: 1.00 s_1: 0.82 s_2: 0.82 s_3: 0.00
time: 359.526318 s
J: -90.942385
Final Chi^2_1: 0.000000 Chi^2_2: 0.148237  Chi^2_3: 1.000000
CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
done.
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x44a2910>> ignored`

**Comment by achael** [comment]
Hi Joe, 

The "clipped pixel" printout is a little confusing, sorry about that! What it means when it says: "Total Pixel #: 16384 and Clipped Pixel #: 16384." is that it hasn't clipped any pixels. The second number should really say "Pixel # after clipping" or something like that -- I'll fix this soon. 

As for the closure phase chi^2, it is a little worrying that you are getting zero  throughout -- I've never seen this behavior. Maybe the error bars on the closure phase have been inflated somehow? If you plot them on a given triangle with 

obs.plot_cphase(site1, site2, site3)

do the error bars look all right? 

If you are ok with letting me me look at the data file you are working with, I'm also happy to look into what's going on here directly. 

Andrew
