### ISSUE TITLE
Congratulations on the big achievement!

### ISSUE THREAD

**Issue by mehulmpt** [achael/eht-imaging#90]
Sorry to open this as an issue, but I really wanted to say congrats to your whole team who made it possible to achieve something truly incredible. I really wish people could admire work like this a billion times than all the celebrities and stuff they usually admire. Brilliant work and kudos to your complete team!

@chanchikwan @lindyblackburn @klbouman @danielpalumbo @jrfarah 

:DDDDDDD

**Comment by IamManchanda** [comment]
Hi Repo Lead @achael (& overall Project lead @klbouman) ... 

I found you guys while reading the thread https://twitter.com/thisgreyspirit/status/1116518551291158528

I am a JavaScript Developer myself with some good programming background and Learning Python (Intermediate) ... I would like to contribute in this overall project as we the humans **scale** now even more ahead ... Let me know if there is a chance

I am here from New Delhi, India! Cheers Mate!

PS: Great Ted Talk 2 years back on same @klbouman ... You guys did it!
https://www.youtube.com/watch?v=BIvezCVcsYs

**Comment by ajtruex** [comment]
![blackhole](https://user-images.githubusercontent.com/16868226/56078640-65839a80-5db8-11e9-8ed4-1f7ff9f6d1e4.jpg)
